version: "3.9"
services:
  alpha:
    build: .
    env_file:
      - .env
    profiles: ["exclude-from-up"]
    volumes:
      - ./alpha_workspace:/app/alpha/alpha_workspace
      - ./data:/app/data
      ## allow alpha to write logs to disk
      - ./logs:/app/logs
      ## uncomment following lines if you want to make use of these files
      ## you must have them existing in the same folder as this docker-compose.yml
      #- type: bind
      #  source: ./azure.yaml
      #  target: /app/azure.yaml
      - type: bind
        source: ./ai_settings.yaml
        target: /app/ai_settings.yaml
      - type: bind
        source: ./prompt_settings.yaml
        target: /app/prompt_settings.yaml
